# Generated by Django 3.2 on 2021-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobreNome', models.CharField(max_length=50)),
                ('dataNasc', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(blank=True, max_length=60, unique=True)),
                ('dataCadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
